# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ayuz-TlYPVjp7i4CuGEiUlfNq4om3s3d
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


st.set_page_config(
    page_title="AI Agent Recommendation",
    layout="wide"
)

st.title("Phân tích và khuyến nghị ứng dụng AI Agent trong lĩnh vực CS/IT")

st.write("""
Ứng dụng này phân tích các task thuộc lĩnh vực Khoa học máy tính / Công nghệ thông tin,
sau đó tính Agent Score và phân loại task thành AI Agent, AI Copilot hoặc Human-in-the-loop.
""")


@st.cache_data
def load_and_process_data():
    # 1. Đọc dữ liệu
    df_task = pd.read_csv("task_statement_with_metadata.csv", low_memory=False)
    df_capability = pd.read_csv("expert_rated_technological_capability.csv", low_memory=False)
    df_desire = pd.read_csv("domain_worker_desires.csv", low_memory=False)

    # 2. Làm sạch dữ liệu
    df_task["Task ID"] = df_task["Task ID"].astype(str)
    df_capability["Task ID"] = df_capability["Task ID"].astype(str)
    df_desire["Task ID"] = df_desire["Task ID"].astype(str)

    df_capability = df_capability.drop_duplicates()

    expert_cols = [
        "Automation Capacity Rating",
        "Physical Action Requirement",
        "Involved Uncertainty",
        "Domain Expertise Requirement",
        "Interpersonal Communication Requirement",
        "Human Agency Scale Rating"
    ]

    for col in expert_cols:
        if col in df_capability.columns:
            df_capability[col] = pd.to_numeric(df_capability[col], errors="coerce")

    worker_cols = [
        "Automation Desire Rating",
        "Time",
        "Core Skill Rating",
        "Job Security Rating",
        "Enjoyment Rating",
        "Physical Action Requirement",
        "Interpersonal Communication Requirement",
        "Involved Uncertainty",
        "Domain Expertise Requirement",
        "Human Agency Scale Rating"
    ]

    for col in worker_cols:
        if col in df_desire.columns:
            df_desire[col] = pd.to_numeric(df_desire[col], errors="coerce")

    # 3. Lọc các nghề liên quan đến CS/IT
    cs_keywords = (
        "Computer|Software|Web|Database|Network|Developer|Analyst|"
        "Programmer|Information|Systems|Data|Cyber|Security"
    )

    cs_occupations = df_task[
        df_task["Occupation (O*NET-SOC Title)"].astype(str).str.contains(
            cs_keywords,
            case=False,
            na=False
        )
    ].copy()

    cs_task_ids = cs_occupations["Task ID"].unique()

    # 4. Lọc expert và worker theo task CS/IT
    cs_expert_eval = df_capability[
        df_capability["Task ID"].isin(cs_task_ids)
    ].copy()

    cs_worker_eval = df_desire[
        df_desire["Task ID"].isin(cs_task_ids)
    ].copy()

    # 5. Tổng hợp expert theo từng task
    expert_task_score = (
        cs_expert_eval
        .groupby("Task ID", as_index=False)
        .agg(
            expert_rating_count=("Automation Capacity Rating", "count"),
            automation_capacity_mean=("Automation Capacity Rating", "mean"),
            physical_mean=("Physical Action Requirement", "mean"),
            uncertainty_mean=("Involved Uncertainty", "mean"),
            domain_expertise_mean=("Domain Expertise Requirement", "mean"),
            interpersonal_mean=("Interpersonal Communication Requirement", "mean"),
            human_agency_mean=("Human Agency Scale Rating", "mean")
        )
    )

    # 6. Tổng hợp worker theo từng task
    worker_task_score = (
        cs_worker_eval
        .groupby("Task ID", as_index=False)
        .agg(
            worker_rating_count=("Automation Desire Rating", "count"),
            automation_desire_mean=("Automation Desire Rating", "mean"),
            time_mean=("Time", "mean"),
            core_skill_mean=("Core Skill Rating", "mean"),
            job_security_mean=("Job Security Rating", "mean"),
            enjoyment_mean=("Enjoyment Rating", "mean"),
            worker_physical_mean=("Physical Action Requirement", "mean"),
            worker_interpersonal_mean=("Interpersonal Communication Requirement", "mean"),
            worker_uncertainty_mean=("Involved Uncertainty", "mean"),
            worker_domain_expertise_mean=("Domain Expertise Requirement", "mean"),
            worker_human_agency_mean=("Human Agency Scale Rating", "mean")
        )
    )

    # 7. Ghép dữ liệu task + expert + worker
    task_info_cols = [
        "Task ID",
        "Occupation (O*NET-SOC Title)",
        "O*NET-SOC Code",
        "Task",
        "Task Type",
        "Occupation Mean Annual Wage",
        "Occupation Employment",
        "Skill (O*NET Work Activity)"
    ]

    task_info_cols = [
        col for col in task_info_cols
        if col in cs_occupations.columns
    ]

    task_info = cs_occupations[task_info_cols].drop_duplicates(subset=["Task ID"])

    df_result = (
        task_info
        .merge(expert_task_score, on="Task ID", how="left")
        .merge(worker_task_score, on="Task ID", how="left")
    )

    # 8. Tính Human Need
    human_need_cols = [
        "physical_mean",
        "uncertainty_mean",
        "domain_expertise_mean",
        "interpersonal_mean",
        "human_agency_mean",
        "worker_physical_mean",
        "worker_uncertainty_mean",
        "worker_domain_expertise_mean",
        "worker_interpersonal_mean",
        "worker_human_agency_mean"
    ]

    available_human_cols = [
        col for col in human_need_cols
        if col in df_result.columns
    ]

    df_result["human_need_mean"] = df_result[available_human_cols].mean(axis=1)

    # Nếu thiếu dữ liệu thì thay bằng mức trung bình 3
    df_result["automation_capacity_mean"] = df_result["automation_capacity_mean"].fillna(3)
    df_result["automation_desire_mean"] = df_result["automation_desire_mean"].fillna(3)
    df_result["time_mean"] = df_result["time_mean"].fillna(3)
    df_result["human_need_mean"] = df_result["human_need_mean"].fillna(3)

    # 9. Tính Agent Score
    def normalize_1_to_5(x):
        return (x - 1) / 4

    df_result["agent_score"] = 100 * (
        0.45 * normalize_1_to_5(df_result["automation_capacity_mean"]) +
        0.30 * normalize_1_to_5(df_result["automation_desire_mean"]) +
        0.15 * normalize_1_to_5(df_result["time_mean"]) -
        0.25 * normalize_1_to_5(df_result["human_need_mean"])
    )

    df_result["agent_score"] = df_result["agent_score"].clip(0, 100).round(2)

    # 10. Phân loại task
    def classify_task(row):
        capacity = row["automation_capacity_mean"]
        desire = row["automation_desire_mean"]
        human_need = row["human_need_mean"]
        score = row["agent_score"]

        if capacity >= 4 and desire >= 3.5 and human_need <= 3.3 and score >= 60:
            return "AI Agent"
        elif capacity >= 3 and desire >= 3 and human_need <= 4:
            return "AI Copilot"
        else:
            return "Human-in-the-loop"

    df_result["Recommendation"] = df_result.apply(classify_task, axis=1)

    # 11. Giải thích khuyến nghị
    def explain_task(row):
        rec = row["Recommendation"]
        capacity = row["automation_capacity_mean"]
        desire = row["automation_desire_mean"]
        human_need = row["human_need_mean"]

        if rec == "AI Agent":
            return (
                f"Task này phù hợp để dùng AI Agent vì expert đánh giá khả năng tự động hóa cao "
                f"({capacity:.2f}/5), worker có nhu cầu tự động hóa tương đối cao "
                f"({desire:.2f}/5), và mức độ cần con người không quá lớn "
                f"({human_need:.2f}/5)."
            )

        elif rec == "AI Copilot":
            return (
                f"Task này phù hợp để dùng AI Copilot vì AI có thể hỗ trợ đáng kể "
                f"({capacity:.2f}/5), nhưng vẫn cần con người kiểm tra, điều chỉnh "
                f"hoặc ra quyết định cuối cùng. Mức cần con người là {human_need:.2f}/5."
            )

        else:
            return (
                f"Task này nên áp dụng Human-in-the-loop vì khả năng tự động hóa chưa đủ cao "
                f"hoặc task còn cần nhiều chuyên môn, giao tiếp, xử lý bất định "
                f"hay sự kiểm soát của con người. Mức cần con người là {human_need:.2f}/5."
            )

    df_result["Explanation"] = df_result.apply(explain_task, axis=1)

    round_cols = [
        "automation_capacity_mean",
        "automation_desire_mean",
        "time_mean",
        "human_need_mean",
        "agent_score"
    ]

    for col in round_cols:
        df_result[col] = df_result[col].round(2)

    return df_task, df_capability, df_desire, cs_occupations, df_result


df_task, df_capability, df_desire, cs_occupations, df_result = load_and_process_data()


# =========================
# PHẦN GIAO DIỆN STREAMLIT
# =========================

st.success("Đã tải và xử lý dữ liệu thành công")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Tổng số task ban đầu", df_task.shape[0])

with col2:
    st.metric("Số task CS/IT", cs_occupations.shape[0])

with col3:
    st.metric("Số nghề CS/IT", cs_occupations["Occupation (O*NET-SOC Title)"].nunique())

with col4:
    st.metric("Số task AI Agent", (df_result["Recommendation"] == "AI Agent").sum())


st.subheader("1. Bảng kết quả sau khi tính Agent Score")

show_cols = [
    "Task ID",
    "Occupation (O*NET-SOC Title)",
    "Task",
    "automation_capacity_mean",
    "automation_desire_mean",
    "time_mean",
    "human_need_mean",
    "agent_score",
    "Recommendation",
    "Explanation"
]

st.dataframe(df_result[show_cols], use_container_width=True)


st.subheader("2. Lọc kết quả theo loại khuyến nghị")

selected_rec = st.selectbox(
    "Chọn loại khuyến nghị",
    ["Tất cả", "AI Agent", "AI Copilot", "Human-in-the-loop"]
)

if selected_rec == "Tất cả":
    filtered_df = df_result.copy()
else:
    filtered_df = df_result[df_result["Recommendation"] == selected_rec]

st.dataframe(filtered_df[show_cols], use_container_width=True)


st.subheader("3. Biểu đồ phân bố điểm khả năng tự động hóa")

fig1, ax1 = plt.subplots(figsize=(8, 5))
sns.histplot(
    data=df_result,
    x="automation_capacity_mean",
    bins=5,
    kde=False,
    ax=ax1
)
ax1.set_title("Phân bố điểm khả năng tự động hóa của các task CS/IT")
ax1.set_xlabel("Điểm trung bình khả năng tự động hóa theo expert")
ax1.set_ylabel("Số lượng task")
st.pyplot(fig1)


st.subheader("4. Biểu đồ số lượng task theo loại khuyến nghị")

order = ["AI Agent", "AI Copilot", "Human-in-the-loop"]

fig2, ax2 = plt.subplots(figsize=(8, 5))
sns.countplot(
    data=df_result,
    x="Recommendation",
    order=order,
    ax=ax2
)
ax2.set_title("Số lượng task theo loại khuyến nghị")
ax2.set_xlabel("Loại khuyến nghị")
ax2.set_ylabel("Số lượng task")
plt.xticks(rotation=15)
st.pyplot(fig2)


st.subheader("5. Agent Score trung bình theo nhóm")

avg_score_by_group = (
    df_result
    .groupby("Recommendation", as_index=False)["agent_score"]
    .mean()
)

avg_score_by_group["agent_score"] = avg_score_by_group["agent_score"].round(2)

fig3, ax3 = plt.subplots(figsize=(8, 5))
sns.barplot(
    data=avg_score_by_group,
    x="Recommendation",
    y="agent_score",
    order=order,
    ax=ax3
)
ax3.set_title("Agent Score trung bình theo nhóm khuyến nghị")
ax3.set_xlabel("Loại khuyến nghị")
ax3.set_ylabel("Agent Score trung bình")
plt.xticks(rotation=15)
st.pyplot(fig3)

st.dataframe(avg_score_by_group, use_container_width=True)


st.subheader("6. Top 10 task có Agent Score cao nhất")

top_10_tasks = df_result.sort_values("agent_score", ascending=False)[
    [
        "Task ID",
        "Occupation (O*NET-SOC Title)",
        "Task",
        "automation_capacity_mean",
        "automation_desire_mean",
        "human_need_mean",
        "agent_score",
        "Recommendation",
        "Explanation"
    ]
].head(10)

st.dataframe(top_10_tasks, use_container_width=True)


st.subheader("7. Danh sách task khuyến nghị AI Agent")

high_potential_agents = (
    df_result[df_result["Recommendation"] == "AI Agent"]
    .sort_values("agent_score", ascending=False)
)

if high_potential_agents.empty:
    st.warning("Không có task nào đạt tiêu chí AI Agent.")
else:
    for _, row in high_potential_agents.head(10).iterrows():
        with st.expander(f"{row['Occupation (O*NET-SOC Title)']} - Agent Score: {row['agent_score']}"):
            st.write("**Tác vụ cụ thể:**", row["Task"])
            st.write("**Khả năng tự động hóa theo expert:**", f"{row['automation_capacity_mean']}/5")
            st.write("**Mong muốn tự động hóa của worker:**", f"{row['automation_desire_mean']}/5")
            st.write("**Mức cần con người:**", f"{row['human_need_mean']}/5")
            st.write("**Giải thích:**", row["Explanation"])
